import type { Diet, Product, Slot, Store, StoreId } from "./types";
export const stores: Store[] = [
  {
    id: "goodmarket",
    name: "goodmarket",
    shortName: "Goodmarket",
    color: "#2f624e",
    light: "#e9f0e5",
    subtitle: "Good food. Good days.",
    deliveryFee: 3.99,
  },
  {
    id: "basket",
    name: "basket & co.",
    shortName: "Basket & Co.",
    color: "#ac513e",
    light: "#fbebe5",
    subtitle: "A little more everyday.",
    deliveryFee: 2.99,
  },
  {
    id: "daybreak",
    name: "daybreak",
    shortName: "Daybreak",
    color: "#88652c",
    light: "#f9f0d9",
    subtitle: "Fresh starts here.",
    deliveryFee: 4.49,
  },
];
const plant: Diet[] = [
  "vegan",
  "vegetarian",
  "gluten-free",
  "dairy-free",
  "nut-free",
];
const dairy: Diet[] = ["vegetarian", "gluten-free", "nut-free"];
type Seed = [
  key: string,
  name: string,
  size: string,
  price: number,
  art: string,
  color: string,
  ingredients: string,
  diets?: Diet[],
  allergens?: string[],
];
const seeds: Seed[] = [
  [
    "avocado",
    "Hass avocados",
    "2 count",
    2.49,
    "avocado",
    "#edf0d5",
    "Avocados",
  ],
  [
    "tomato",
    "Vine-ripened tomatoes",
    "1 lb",
    2.79,
    "tomato",
    "#f8e5dc",
    "Tomatoes",
  ],
  [
    "tortillas",
    "Soft corn tortillas",
    "12 count · 10 oz",
    2.29,
    "tortilla",
    "#f7edcf",
    "Corn masa flour, water, lime, salt",
  ],
  [
    "black-beans",
    "Organic black beans",
    "15 oz can",
    1.69,
    "can",
    "#e6e8e7",
    "Organic black beans, water, sea salt",
  ],
  ["lime", "Fresh limes", "3 count", 1.49, "lime", "#edf2d9", "Limes"],
  [
    "cilantro",
    "Fresh cilantro",
    "1 bunch",
    0.99,
    "herb",
    "#e6efdb",
    "Cilantro",
  ],
  ["onion", "Red onion", "1 count", 0.89, "onion", "#eee2ed", "Red onion"],
  [
    "bell-pepper",
    "Sweet bell peppers",
    "3 count",
    3.49,
    "pepper",
    "#fae6d3",
    "Red, yellow and orange bell peppers",
  ],
  [
    "rice",
    "Long grain brown rice",
    "1 lb bag",
    2.29,
    "bag",
    "#efe9da",
    "Whole grain brown rice",
  ],
  [
    "tofu",
    "Organic extra-firm tofu",
    "14 oz",
    2.99,
    "box",
    "#e7ede0",
    "Water, organic soybeans, calcium sulfate",
    plant,
    ["soy"],
  ],
  [
    "chicken",
    "Boneless chicken breast",
    "1 lb",
    5.99,
    "tray",
    "#fae9dd",
    "Chicken breast",
    ["gluten-free", "dairy-free", "nut-free"],
  ],
  [
    "salmon",
    "Atlantic salmon fillets",
    "12 oz · 2 portions",
    9.99,
    "tray",
    "#f7e0d4",
    "Atlantic salmon",
    ["gluten-free", "dairy-free", "nut-free"],
    ["fish"],
  ],
  [
    "pasta",
    "Bronze-cut penne",
    "16 oz",
    1.99,
    "pasta",
    "#f9edd3",
    "Durum wheat semolina",
    ["vegan", "vegetarian", "dairy-free", "nut-free"],
    ["wheat"],
  ],
  [
    "pasta-sauce",
    "Tomato & basil sauce",
    "24 oz jar",
    3.49,
    "jar",
    "#f4e2d8",
    "Tomatoes, olive oil, basil, garlic, sea salt",
  ],
  [
    "spinach",
    "Baby spinach",
    "5 oz",
    2.49,
    "herb",
    "#e5eddd",
    "Organic baby spinach",
  ],
  [
    "mushroom",
    "Baby bella mushrooms",
    "8 oz",
    2.79,
    "mushroom",
    "#eee7de",
    "Baby bella mushrooms",
  ],
  ["garlic", "Fresh garlic", "1 bulb", 0.69, "garlic", "#f0ece1", "Garlic"],
  [
    "olive-oil",
    "Extra virgin olive oil",
    "8.5 fl oz",
    4.99,
    "bottle",
    "#e8ebd9",
    "Extra virgin olive oil",
  ],
  [
    "cheese",
    "Shredded mild cheddar",
    "8 oz",
    2.99,
    "bag",
    "#fae6c8",
    "Pasteurized milk, cheese cultures, salt, enzymes",
    dairy,
    ["milk"],
  ],
  [
    "milk",
    "Whole milk",
    "Half gallon",
    3.29,
    "carton",
    "#e4edf3",
    "Grade A pasteurized whole milk, vitamin D3",
    dairy,
    ["milk"],
  ],
  [
    "oat-milk",
    "Unsweetened oat milk",
    "32 fl oz",
    3.49,
    "carton",
    "#f0e8d8",
    "Filtered water, certified gluten-free oats, sunflower oil, sea salt",
  ],
  [
    "eggs",
    "Free-range large eggs",
    "12 count",
    3.99,
    "eggs",
    "#f1e8d7",
    "Eggs",
    ["vegetarian", "gluten-free", "dairy-free", "nut-free"],
    ["egg"],
  ],
  [
    "yogurt",
    "Plain Greek yogurt",
    "32 oz",
    4.49,
    "tub",
    "#e7edf4",
    "Cultured pasteurized nonfat milk, live active cultures",
    dairy,
    ["milk"],
  ],
  [
    "oats",
    "Gluten-free rolled oats",
    "18 oz",
    2.99,
    "can",
    "#ede5d5",
    "Certified gluten-free whole grain oats",
  ],
  [
    "banana",
    "Organic bananas",
    "5 count",
    1.49,
    "banana",
    "#f8f0cf",
    "Bananas",
  ],
  [
    "berries",
    "Fresh blueberries",
    "6 oz",
    3.29,
    "berries",
    "#e8e4f2",
    "Blueberries",
  ],
  [
    "bread",
    "Sourdough sandwich bread",
    "18 oz loaf",
    3.99,
    "bread",
    "#f3e7d2",
    "Wheat flour, water, sourdough culture, salt",
    ["vegan", "vegetarian", "dairy-free", "nut-free"],
    ["wheat"],
  ],
  [
    "peanut-butter",
    "Creamy peanut butter",
    "16 oz",
    2.49,
    "jar",
    "#f2dfc4",
    "Roasted peanuts, salt",
    ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    ["peanut"],
  ],
  [
    "chickpeas",
    "Organic chickpeas",
    "15 oz can",
    1.49,
    "can",
    "#efe9d9",
    "Organic chickpeas, water, sea salt",
  ],
  [
    "cucumber",
    "English cucumber",
    "1 count",
    1.29,
    "cucumber",
    "#e3eddb",
    "Cucumber",
  ],
  [
    "lettuce",
    "Romaine hearts",
    "3 count",
    2.99,
    "herb",
    "#e6efdd",
    "Romaine lettuce",
  ],
  ["lemon", "Fresh lemons", "3 count", 1.79, "lemon", "#f8f0d3", "Lemons"],
  [
    "hummus",
    "Classic hummus",
    "8 oz",
    2.99,
    "tub",
    "#f2e8d8",
    "Chickpeas, tahini, olive oil, lemon juice, garlic, salt",
    plant,
    ["sesame"],
  ],
  [
    "quinoa",
    "Organic white quinoa",
    "12 oz",
    3.99,
    "bag",
    "#eee7dc",
    "Organic white quinoa",
  ],
  ["broccoli", "Broccoli crowns", "1 lb", 1.99, "herb", "#e2eada", "Broccoli"],
  [
    "sweet-potato",
    "Sweet potatoes",
    "2 lb bag",
    2.99,
    "potato",
    "#f5e4d5",
    "Sweet potatoes",
  ],
  [
    "salsa",
    "Roasted tomato salsa",
    "16 oz",
    2.49,
    "jar",
    "#f4e1d4",
    "Tomatoes, onion, jalapeno, cilantro, lime juice, salt",
  ],
  [
    "corn",
    "Sweet corn",
    "15 oz can",
    1.29,
    "can",
    "#f8edc7",
    "Sweet corn, water, salt",
  ],
  [
    "coffee",
    "House blend coffee",
    "12 oz",
    6.99,
    "bag",
    "#e9dfd3",
    "100% Arabica coffee",
  ],
  [
    "sparkling-water",
    "Lime sparkling water",
    "8 × 12 fl oz",
    3.99,
    "can",
    "#e4ece6",
    "Carbonated water, natural lime flavor",
  ],
];
export const catalogKeys = seeds.map((s) => s[0]);
export const catalogLabels: Record<string, string> = {
  ...Object.fromEntries(seeds.map((s) => [s[0], s[1]])),
  tortillas: "Tortillas",
  pasta: "Pasta",
  cheese: "Cheese",
  milk: "Milk",
  yogurt: "Yogurt",
  bread: "Bread",
};
export const money = (n: number) =>
  new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(
    n / 100,
  );
export const getStore = (id: StoreId) => stores.find((s) => s.id === id)!;
export function productsFor(store: StoreId): Product[] {
  const storeIndex = stores.findIndex((s) => s.id === store);
  const products = seeds.map((s, index): Product => {
    const adjustment = [
      [0, 10, -10, 20, 0, 10, 0],
      [20, -30, 10, -10, 20, 0, 10],
      [40, 0, 30, -20, -10, 20, 10],
    ][storeIndex][index % 7];
    return {
      id: `${store}-${s[0]}`,
      key: s[0],
      name: s[1],
      brand: ["Goodmarket kitchen", "Basket everyday", "Daybreak essentials"][
        storeIndex
      ],
      size: s[2],
      price: Math.round(s[3] * 100) + adjustment,
      unit: "package",
      art: s[4],
      color: s[5],
      ingredients: s[6],
      diets: s[7] ?? plant,
      allergens: s[8] ?? [],
      mayContain: [],
      stock: true,
    };
  });
  const variants: [string, string, string, number, string, Diet[], string[]][] =
    [
      [
        "pasta",
        "Gluten-free brown rice penne",
        "Brown rice flour, water",
        100,
        "16 oz",
        plant,
        [],
      ],
      [
        "cheese",
        "Plant-based cheddar shreds",
        "Filtered water, coconut oil, potato starch, salt",
        80,
        "8 oz",
        plant,
        [],
      ],
      [
        "milk",
        "Unsweetened oat milk",
        "Water, certified gluten-free oats, sunflower oil, sea salt",
        30,
        "Half gallon",
        plant,
        [],
      ],
      [
        "yogurt",
        "Unsweetened coconut yogurt",
        "Coconut cream, tapioca starch, live active cultures",
        60,
        "32 oz",
        plant,
        [],
      ],
      [
        "bread",
        "Gluten-free seeded loaf",
        "Rice flour, water, tapioca starch, sunflower seeds, yeast, salt",
        120,
        "18 oz",
        plant,
        [],
      ],
      [
        "tortillas",
        "Soft flour tortillas",
        "Wheat flour, water, vegetable oil, salt",
        -30,
        "12 count · 10 oz",
        ["vegan", "vegetarian", "dairy-free", "nut-free"],
        ["wheat"],
      ],
    ];
  for (const [
    key,
    name,
    ingredients,
    extra,
    size,
    diets,
    allergens,
  ] of variants) {
    const base = products.find((p) => p.key === key)!;
    products.push({
      ...base,
      id: `${base.id}-alternative`,
      name,
      ingredients,
      price: base.price + extra,
      size,
      diets,
      allergens,
    });
  }
  return products;
}
export function deliverySlots(): Slot[] {
  return [
    {
      id: "soon",
      label: "Today · in about 45 min",
      preference: "today",
      fee: 200,
      available: true,
    },
    {
      id: "tomorrow-am",
      label: "Tomorrow · 9–10 am",
      preference: "tomorrow-morning",
      fee: 0,
      available: true,
    },
    {
      id: "tomorrow-pm",
      label: "Tomorrow · 2–3 pm",
      preference: "tomorrow-afternoon",
      fee: 0,
      available: true,
    },
    {
      id: "tomorrow-eve",
      label: "Tomorrow · 5–6 pm",
      preference: "tomorrow-evening",
      fee: 0,
      available: true,
    },
    {
      id: "tomorrow-late",
      label: "Tomorrow · 6–7 pm",
      preference: "tomorrow-evening",
      fee: 100,
      available: false,
    },
  ];
}
export const examples = [
  {
    title: "Taco night, handled.",
    subtitle: "Dinner for four, without the dairy.",
    icon: "taco",
    prompt:
      "Get everything for dairy-free veggie tacos for 4, under $35. Deliver tomorrow evening.",
  },
  {
    title: "A better kind of morning.",
    subtitle: "A week of easy, gluten-free breakfasts.",
    icon: "breakfast",
    prompt:
      "Stock up on gluten-free breakfasts for 2 for the week: oats, oat milk, bananas, blueberries and yogurt. Under $40, tomorrow morning.",
  },
  {
    title: "Dinner plans? Done.",
    subtitle: "A cozy pasta night for two.",
    icon: "pasta",
    prompt:
      "Shop for a vegan pasta dinner for 2 with tomatoes, mushrooms and spinach. Keep it under $25 and deliver today.",
  },
];
